name: importance_of_bandwidth
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.0.1
  - numpy=1.21.2
  - pandas=1.2.3
  - seaborn=0.11.1
  - notebook=6.3.0
  - pip:
    - matplotlib==3.4.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - qiskit==0.29.0
    - qiskit-machine-learning==0.2.1
    - tqdm==4.59.0
